---
- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: true

- name: Restart TravelMemory
  ansible.builtin.service:
    name: travelmemory
    state: restarted
    enabled: true

- name: Restart Nginx
  ansible.builtin.service:
    name: nginx
    state: restarted
    enabled: true
